name: Node.js CI

on:
  push:
    branches: [ "Assignment1", "main" ]
  pull_request:
    branches: [ "Assignment1", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Required permissions to post comments on Pull Requests
    permissions:
      pull-requests: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Run ESLint
      run: npx eslint . --ext .ts

    - name: Build
      run: npm run build

    - name: Jest Coverage Comment
      if: github.event_name == 'pull_request'
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-script: npm run test:coverage
        annotations: failed-tests

    - name: Run Tests (Push Events)
      if: github.event_name == 'push'
      run: npm run test:coverage

